DO $roles$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cresco_app') THEN
    CREATE ROLE cresco_app LOGIN PASSWORD 'cresco_app_dev' NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END
$roles$;

GRANT CONNECT ON DATABASE cresco TO cresco_app;
GRANT USAGE ON SCHEMA public TO cresco_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cresco_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cresco_app;

ALTER DEFAULT PRIVILEGES FOR ROLE cresco_admin IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cresco_app;
ALTER DEFAULT PRIVILEGES FOR ROLE cresco_admin IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO cresco_app;
